apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: LoadBalancer
  selector:
    app: bankapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
